spring:
  profiles:
    group:
      local: local, datasource
      prod: prod, datasource

  # Spring Security
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID} # idToken.aud에 해당
        provider:
          kakao:
            issuer-uri: "https://kauth.kakao.com"
            jwk-set-uri: "https://kauth.kakao.com/.well-known/jwks.json"

app:
  jwt:
    issuer: "api.goforawalk.site"
    user-name-attribute: "sub"
    at-secret-key: ${JWT_AT_SECRET_KEY}
    rt-secret-key: ${JWT_RT_SECRET_KEY}
    at-expiration-seconds: ${JWT_AT_EXPIRATION_SECONDS}
    rt-expiration-seconds: ${JWT_RT_EXPIRATION_SECONDS}

gcp:
  project-id: ${GCP_PROJECT_ID}
  storage:
    bucket: ${GCP_STORAGE_BUCKET}
    credentials:
      encoded-key: ${GCP_STORAGE_CREDENTIALS_ENCODED_KEY}

oci:
  region: ${OCI_BUCKET_REGION}          # 1. OCI 리전 (예: ap-chuncheon-1)
  namespace: ${OCI_BUCKET_NAMESPACE}    # 2. OCI 콘솔에서 확인한 Object Storage 네임스페이스
  bucket-name: ${OCI_BUCKET_NAME}       # 3. 이미지를 업로드할 버킷의 이름
  config-path: ${OCI_BUCKET_CONFIG_PATH} # 4. OCI 설정 파일의 경로 (보통 이 경로를 그대로 사용)
  config-profile: ${OCI_BUCKET_CONFIG_PROFILE} # 5. 설정 파일 내에서 사용할 프로필 이름 (보통 DEFAULT)
