spring:
  profiles:
    group:
      local: local, datasource
      prod: prod, datasource

  # Spring Security
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID} # idToken.aud에 해당
          apple:
            client-id: ${APPLE_CLIENT_ID} # idToken.aud에 해당
        provider:
          kakao:
            issuer-uri: https://kauth.kakao.com
            jwk-set-uri: https://kauth.kakao.com/.well-known/jwks.json
          apple:
            issuer-uri: https://appleid.apple.com
            # Apple Public Key: https://developer.apple.com/documentation/signinwithapplerestapi/fetch_apple_s_public_key_for_verifying_token_signature
            jwk-set-uri: https://appleid.apple.com/auth/keys

app:
  jwt:
    issuer: api.goforawalk.site
    user-name-attribute: "sub"
    at-secret-key: ${JWT_AT_SECRET_KEY}
    rt-secret-key: ${JWT_RT_SECRET_KEY}
    at-expiration-seconds: ${JWT_AT_EXPIRATION_SECONDS}
    rt-expiration-seconds: ${JWT_RT_EXPIRATION_SECONDS}

gcp:
  project-id: ${GCP_PROJECT_ID}
  storage:
    bucket: ${GCP_STORAGE_BUCKET}
    credentials:
      encoded-key: ${GCP_STORAGE_CREDENTIALS_ENCODED_KEY}

sentry:
  dsn: ${SENTRY_DSN}
  # Add data like request headers and IP for users,
  # see https://docs.sentry.io/platforms/java/guides/spring-boot/data-management/data-collected/ for more info
  send-default-pii: true
#  traces-sample-rate: 1.0
  # Sentry 로깅 레벨 설정
#  logging:
#    minimum-event-level: error # Sentry로 전송할 최소 이벤트(에러) 레벨 (error 이상만 Sentry에 전송)
#    minimum-breadcrumb-level: info # Sentry에 기록할 최소 breadcrumb(추적정보) 레벨 (info 이상 기록)